### ISSUE TITLE
Structure repo pour projet ML Ops

### ISSUE THREAD

**Issue by mis7ern9o** [DstMlOpsCrypto/MainCrypto#14]
### Discussed in https://github.com/DstMlOpsCrypto/MainCrypto/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **mis7ern9o** August  3, 2024</sup>
Avec les différentes lectures effectuées, voici un template de structures de repo pour un projet ML Ops standard qui viendrait compléter ce que tu as déjà fait @FredericLAGNIEZ 

mlops-crypto-prediction/
├── data/
│   ├── raw/                # Données brutes non traitées
│   ├── processed/          # Données traitées et prêtes pour l'analyse
│   └── external/           # Données provenant de sources externes
├── notebooks/
│   ├── exploration/        # Notebooks pour l'analyse exploratoire des données
│   └── modeling/           # Notebooks pour la modélisation et l'entraînement
├── src/
│   ├── data/               # Scripts pour la collecte et la préparation des données
│   ├── models/             # Scripts pour la définition et l'entraînement des modèles
│   ├── evaluation/         # Scripts pour l'évaluation des modèles
│   └── deployment/         # Scripts pour le déploiement des modèles
├── tests/
│   ├── unit/               # Tests unitaires pour les scripts
│   └── integration/        # Tests d'intégration pour les pipelines
├── config/
│   ├── config.yaml         # Fichiers de configuration pour les paramètres du projet
│   └── logging.yaml        # Configuration pour la journalisation
├── scripts/
│   ├── preprocess.py       # Script pour la préparation des données
│   ├── train.py            # Script pour l'entraînement des modèles
│   ├── evaluate.py         # Script pour l'évaluation des modèles
│   └── deploy.py           # Script pour le déploiement des modèles
├── .github/
│   ├── workflows/          # Workflows GitHub Actions pour CI/CD
│   └── ISSUE_TEMPLATE.md   # Modèle pour les issues
├── Dockerfile              # Fichier Docker pour la création de l'image du projet
├── requirements.txt        # Liste des dépendances du projet
├── README.md               # Documentation du projet
└── LICENSE                 # Licence du projet

A disposition pour en discuter </div>

**Comment by FredericLAGNIEZ** [comment]
parfait pour moi, J'avais repris à ce stade repris le modèle de Sébastien comme points de départ

Dans src, je rajouterai juste utils et features

├── src/
│ ├── data/ # Scripts pour la collecte et la préparation des données
│ ├── models/ # Scripts pour la définition et l'entraînement des modèles
│ ├── evaluation/ # Scripts pour l'évaluation des modèles
│ ├── utils / # script pour les fonctions utilitaires
│ ├── features / # script pour le traitement des variables
│ └── deployment/ # Scripts pour le déploiement des modèles

Et je suggère de garder le fichier setup.py à la racine # gestion des dépendances, distribuer le code, automatiser les tâches et fournir des métadonnées 

Je modifie le repo si cela vous va

**Comment by mis7ern9o** [comment]
modif prises en compte
