### ISSUE TITLE
Create script table user 

### ISSUE THREAD

**Issue by mis7ern9o** [DstMlOpsCrypto/MainCrypto#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TWR-RWT** [comment]
Pour la création de la table tu peux partir sur la structure ci-dessous. C'est la structure sur laquelle je suis partis quand j'ai construit les premières fonctionnalités d'authentification de l'API. Si vous pensez qu'il manque des choses n'hésitez pas à proposer une autre structure de table.

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user'
);

**Comment by mis7ern9o** [comment]
need to re arrange the bash file : 
- cleaning code (redondancy)
- add json load
- maybe extract data OHVLT data to individual script for the futur cron job
