### ISSUE TITLE
Model overview analysis

### ISSUE THREAD

**Issue by mis7ern9o** [DstMlOpsCrypto/MainCrypto#5]

**Comment by FredericLAGNIEZ** [comment]
Hello la team, voici une analyse des modèles qui pourra servir à définir notre problématique et alimenter le rapport

https://kdrive.infomaniak.com/app/share/771182/de361e10-da54-43f2-98cd-f13c92ad960f

(il s'agit d'un document partagé que vous pouvez amender, en prenant soin de faire apparaitre vos modifs)

Frédéric

**Comment by mis7ern9o** [comment]
update du wiki a réaliser

**Comment by mis7ern9o** [comment]
analyse effectuée
